[[IPOMDPs]]
git-tree-sha1 = "7c6f9c64f6e8ea609b76ab93622daf803cb6a742"
repo-rev = "master"
repo-url = "git@gitlab.com:iacosite/ipomdps.git"
uuid = "400b8fa6-c29f-11e8-147f-97038bb7f9c1"
version = "0.1.0"
