name = "IPOMDPToolbox"
uuid = "4bc94e48-c29f-11e8-07ee-0ffc18eb0ae4"
authors = ["Iacopo Olivo <iacopo.olivo@gmail.com>"]
version = "0.1.0"

[deps]
IPOMDPs = "400b8fa6-c29f-11e8-147f-97038bb7f9c1"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
